// <auto-generated />
namespace Coinage.Data.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Customer_Add_Entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Customer_Add_Entity));
        
        string IMigrationMetadata.Id
        {
            get { return "201402031238584_Customer_Add_Entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
